#!/usr/bin/env python3
"""Sprite editor tooling — export sprites to browser editor, apply changes back.

Usage:
    poetry run sprite-editor          # exports data + opens editor
    poetry run sprite-editor apply    # applies changes from editor

The default command reads all sprite data from Python modules, resolves Rich
color names to hex RGB, writes tools/sprite_data.js, starts a local server,
and opens the editor in the default browser.

The apply command reads tools/sprite_data.js (updated by the editor's Save
button) and regenerates the Python sprite data files.
"""

import argparse
import json
import re
import shutil
import sys
import threading
import webbrowser
from functools import partial
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from tools.sprite_export import build_export_data
from tools.sprite_gen_facility import (
    generate_facility_close_source,
    generate_facility_pixels_source,
)
from tools.sprite_gen_pig import (
    generate_close_pig_source,
    generate_pig_sprites_source,
)

TOOLS_DIR = Path(__file__).resolve().parent
SPRITE_DATA_JS = TOOLS_DIR / "sprite_data.js"
WORKSPACE_DIR = TOOLS_DIR / "sprite_workspace"
BACKUP_DIR = WORKSPACE_DIR / "backup"

# Sprite data source files (for apply/backup)
DATA_DIR = PROJECT_ROOT / "big_pig_farm" / "data"
PIG_SPRITES_FILE = DATA_DIR / "pig_sprites.py"
PIG_SPRITES_CLOSE_FILE = DATA_DIR / "pig_sprites_close.py"
FACILITY_PIXELS_FILE = DATA_DIR / "facility_pixels.py"
FACILITY_PIXELS_CLOSE_FILE = DATA_DIR / "facility_pixels_close.py"


def _write_sprite_data_js(json_str: str) -> None:
    """Write sprite data as a JS module."""
    SPRITE_DATA_JS.write_text(
        f"// Auto-generated by sprite_editor.py — do not edit\n"
        f"const DATA = {json_str};\n",
        encoding="utf-8",
    )


def _read_sprite_data_js() -> dict:
    """Read and parse JSON from sprite_data.js."""
    text = SPRITE_DATA_JS.read_text(encoding="utf-8")
    m = re.search(r"^const DATA = ({.*});$", text, re.DOTALL | re.MULTILINE)
    if not m:
        print("Error: could not parse sprite_data.js")
        sys.exit(1)
    return json.loads(m.group(1))


# ---------------------------------------------------------------------------
# Local server for the editor
# ---------------------------------------------------------------------------

class _EditorHandler(SimpleHTTPRequestHandler):
    """Serves the tools/ directory and handles POST /save."""

    def do_POST(self) -> None:
        if self.path == "/save":
            length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(length)
            _write_sprite_data_js(body.decode("utf-8"))
            self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(b"OK")
            print(f"Saved changes to {SPRITE_DATA_JS}")
        else:
            self.send_error(404)

    def log_message(self, format: str, *args: object) -> None:
        pass


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def cmd_export() -> None:
    """Export sprite data, start local server, and open the editor."""
    data = build_export_data()
    _write_sprite_data_js(json.dumps(data, indent=2))
    print(f"Exported sprite data to {SPRITE_DATA_JS}")

    handler = partial(_EditorHandler, directory=str(TOOLS_DIR))
    server = HTTPServer(("127.0.0.1", 0), handler)
    port = server.server_address[1]
    url = f"http://127.0.0.1:{port}/sprite_editor.html"

    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()

    print(f"Serving editor at {url}")
    print("Press Ctrl+C to stop the server when done editing.")
    webbrowser.open(url)

    try:
        thread.join()
    except KeyboardInterrupt:
        print("\nServer stopped.")
        server.shutdown()


def cmd_apply(json_path: str | None = None) -> None:
    """Apply sprite changes from sprite_data.js (or a JSON file) back to Python source files."""
    if json_path:
        path = Path(json_path)
        if not path.exists():
            print(f"Error: file not found: {path}")
            sys.exit(1)
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    else:
        if not SPRITE_DATA_JS.exists():
            print(f"Error: {SPRITE_DATA_JS} not found.")
            print("Run 'poetry run sprite-editor' and save changes first.")
            sys.exit(1)
        data = _read_sprite_data_js()

    if data.get("format_version") != 1:
        print("Error: unsupported format version")
        sys.exit(1)

    sprites = data["sprites"]

    # Create backup
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    targets = [
        PIG_SPRITES_FILE, PIG_SPRITES_CLOSE_FILE,
        FACILITY_PIXELS_FILE, FACILITY_PIXELS_CLOSE_FILE,
    ]
    for src in targets:
        if src.exists():
            shutil.copy2(src, BACKUP_DIR / src.name)
    print(f"Backups saved to {BACKUP_DIR}/")

    # Read existing sources for facility generators
    facility_source = FACILITY_PIXELS_FILE.read_text(encoding="utf-8")
    facility_close_source = FACILITY_PIXELS_CLOSE_FILE.read_text(encoding="utf-8")

    # Generate sources
    generated: list[tuple[Path, str]] = [
        (PIG_SPRITES_FILE, generate_pig_sprites_source(
            sprites.get("pig_adult", {}),
            sprites.get("pig_baby", {}),
            sprites.get("pig_far_adult", {}),
            sprites.get("pig_far_baby", {}),
        )),
        (PIG_SPRITES_CLOSE_FILE, generate_close_pig_source(
            sprites.get("pig_adult_close", {}),
            sprites.get("pig_baby_close", {}),
        )),
        (FACILITY_PIXELS_FILE, generate_facility_pixels_source(
            sprites.get("facility_normal", {}),
            sprites.get("facility_far", {}),
            facility_source,
        )),
        (FACILITY_PIXELS_CLOSE_FILE, generate_facility_close_source(
            sprites.get("facility_close", {}),
            facility_close_source,
        )),
    ]

    # Validate syntax before writing anything
    for target, src in generated:
        try:
            compile(src, target.name, "exec")
        except SyntaxError as e:
            print(f"Error: generated {target.name} has syntax error: {e}")
            sys.exit(1)

    # Write validated sources
    for target, src in generated:
        target.write_text(src, encoding="utf-8")
        print(f"Wrote {target}")

    print("\nDone! Run 'poetry run sprite-preview --sprites' to verify.")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Sprite editor tooling — export to browser, apply changes back"
    )
    sub = parser.add_subparsers(dest="command")

    sub.add_parser("export", help="Export sprite data and open editor")

    apply_parser = sub.add_parser("apply", help="Apply changes from editor")
    apply_parser.add_argument(
        "json_file", nargs="?", default=None,
        help="Path to JSON file (default: reads from sprite_data.js)",
    )

    args = parser.parse_args()

    if args.command == "apply":
        cmd_apply(args.json_file)
    else:
        cmd_export()


if __name__ == "__main__":
    main()
