#!/usr/bin/env python3
"""Sprite editor tooling — export sprites to browser editor, apply changes back.

Usage:
    poetry run sprite-editor          # exports data + opens editor
    poetry run sprite-editor apply    # applies changes from sprite_data.js

The default command reads all sprite data from Python modules, resolves Rich
color names to hex RGB, writes tools/sprite_data.js, starts a local server,
and opens the editor in the default browser.  Clicking "Export Changes" in
the browser saves to sprite_data.js and automatically applies changes back
to the Python source files.

The apply command manually re-applies from sprite_data.js (or a JSON file).
"""

import argparse
import json
import re
import shutil
import sys
import threading
import webbrowser
from functools import partial
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from tools.sprite_export import build_export_data
from tools.sprite_gen_facility import (
    generate_facility_close_source,
    generate_facility_pixels_source,
)
from tools.sprite_gen_indicator import generate_indicator_pixels_source
from tools.sprite_gen_pig import (
    generate_close_pig_source,
    generate_pig_sprites_source,
)

TOOLS_DIR = Path(__file__).resolve().parent
SPRITE_DATA_JS = TOOLS_DIR / "sprite_data.js"
WORKSPACE_DIR = TOOLS_DIR / "sprite_workspace"
BACKUP_DIR = WORKSPACE_DIR / "backup"

# Sprite data source files (for apply/backup)
DATA_DIR = PROJECT_ROOT / "big_pig_farm" / "data"
PIG_SPRITES_FILE = DATA_DIR / "pig_sprites.py"
PIG_SPRITES_CLOSE_FILE = DATA_DIR / "pig_sprites_close.py"
FACILITY_PIXELS_FILE = DATA_DIR / "facility_pixels.py"
FACILITY_PIXELS_CLOSE_FILE = DATA_DIR / "facility_pixels_close.py"
INDICATOR_PIXELS_FILE = DATA_DIR / "indicator_pixels.py"


def _write_sprite_data_js(json_str: str) -> None:
    """Write sprite data as a JS module."""
    SPRITE_DATA_JS.write_text(
        f"// Auto-generated by sprite_editor.py — do not edit\n"
        f"const DATA = {json_str};\n",
        encoding="utf-8",
    )


def _read_sprite_data_js() -> dict:
    """Read and parse JSON from sprite_data.js."""
    text = SPRITE_DATA_JS.read_text(encoding="utf-8")
    m = re.search(r"^const DATA = ({.*});$", text, re.DOTALL | re.MULTILINE)
    if not m:
        raise ValueError("could not parse sprite_data.js")
    return json.loads(m.group(1))


# ---------------------------------------------------------------------------
# Core apply logic
# ---------------------------------------------------------------------------

def apply_sprite_data(data: dict) -> list[str]:
    """Apply sprite changes from editor data back to Python source files.

    Compares against current source data to only regenerate files whose
    sprite groups actually changed.

    Returns:
        List of messages describing what was done.

    Raises:
        ValueError: If data format is unsupported or generated code has errors.
    """
    if data.get("format_version") != 1:
        raise ValueError("unsupported format version")

    sprites = data["sprites"]

    # Compare against current source data to detect which groups changed
    original = build_export_data()
    original_sprites = original["sprites"]

    def _groups_changed(*group_names: str) -> bool:
        return any(
            sprites.get(g) != original_sprites.get(g) for g in group_names
        )

    # Only regenerate files whose sprite groups actually changed
    generated: list[tuple[Path, str]] = []

    if _groups_changed("pig_adult", "pig_baby", "pig_far_adult", "pig_far_baby"):
        generated.append((PIG_SPRITES_FILE, generate_pig_sprites_source(
            sprites.get("pig_adult", {}),
            sprites.get("pig_baby", {}),
            sprites.get("pig_far_adult", {}),
            sprites.get("pig_far_baby", {}),
        )))

    if _groups_changed("pig_adult_close", "pig_baby_close"):
        generated.append((PIG_SPRITES_CLOSE_FILE, generate_close_pig_source(
            sprites.get("pig_adult_close", {}),
            sprites.get("pig_baby_close", {}),
        )))

    if _groups_changed("facility_normal", "facility_far"):
        facility_source = FACILITY_PIXELS_FILE.read_text(encoding="utf-8")
        generated.append((FACILITY_PIXELS_FILE, generate_facility_pixels_source(
            sprites.get("facility_normal", {}),
            sprites.get("facility_far", {}),
            facility_source,
        )))

    if _groups_changed("facility_close"):
        facility_close_source = FACILITY_PIXELS_CLOSE_FILE.read_text(encoding="utf-8")
        generated.append((FACILITY_PIXELS_CLOSE_FILE, generate_facility_close_source(
            sprites.get("facility_close", {}),
            facility_close_source,
        )))

    if _groups_changed("indicator_normal", "indicator_close"):
        indicator_source = INDICATOR_PIXELS_FILE.read_text(encoding="utf-8")
        generated.append((INDICATOR_PIXELS_FILE, generate_indicator_pixels_source(
            sprites.get("indicator_normal", {}),
            sprites.get("indicator_close", {}),
            indicator_source,
        )))

    if not generated:
        return ["No sprite changes detected — nothing to apply."]

    # Create backup of files we're about to write
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    for target, _ in generated:
        if target.exists():
            shutil.copy2(target, BACKUP_DIR / target.name)

    # Validate syntax before writing anything
    for target, src in generated:
        try:
            compile(src, target.name, "exec")
        except SyntaxError as e:
            raise ValueError(f"generated {target.name} has syntax error: {e}")

    # Write validated sources
    messages = []
    for target, src in generated:
        target.write_text(src, encoding="utf-8")
        messages.append(f"Wrote {target.name}")

    return messages


# ---------------------------------------------------------------------------
# Local server for the editor
# ---------------------------------------------------------------------------

class _EditorHandler(SimpleHTTPRequestHandler):
    """Serves the tools/ directory and handles POST /save."""

    def do_POST(self) -> None:
        if self.path == "/save":
            length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(length)
            data_str = body.decode("utf-8")

            # Save to sprite_data.js
            _write_sprite_data_js(data_str)

            # Auto-apply changes back to Python source files
            try:
                data = json.loads(data_str)
                messages = apply_sprite_data(data)
                for msg in messages:
                    print(f"  {msg}")
                response = "Applied:\n" + "\n".join(messages)
            except (ValueError, json.JSONDecodeError) as e:
                print(f"  Apply error: {e}")
                response = f"Saved to sprite_data.js but apply failed: {e}"

            self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(response.encode("utf-8"))
            print(f"Saved changes to {SPRITE_DATA_JS}")
        else:
            self.send_error(404)

    def log_message(self, format: str, *args: object) -> None:
        pass


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def cmd_export() -> None:
    """Export sprite data, start local server, and open the editor."""
    data = build_export_data()
    _write_sprite_data_js(json.dumps(data, indent=2))
    print(f"Exported sprite data to {SPRITE_DATA_JS}")

    handler = partial(_EditorHandler, directory=str(TOOLS_DIR))
    server = HTTPServer(("127.0.0.1", 0), handler)
    port = server.server_address[1]
    url = f"http://127.0.0.1:{port}/sprite_editor.html"

    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()

    print(f"Serving editor at {url}")
    print("Press Ctrl+C to stop the server when done editing.")
    webbrowser.open(url)

    try:
        thread.join()
    except KeyboardInterrupt:
        print("\nServer stopped.")
        server.shutdown()


def cmd_apply(json_path: str | None = None) -> None:
    """Apply sprite changes from sprite_data.js (or a JSON file) back to Python source files."""
    if json_path:
        path = Path(json_path)
        if not path.exists():
            print(f"Error: file not found: {path}")
            sys.exit(1)
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    else:
        if not SPRITE_DATA_JS.exists():
            print(f"Error: {SPRITE_DATA_JS} not found.")
            print("Run 'poetry run sprite-editor' and save changes first.")
            sys.exit(1)
        data = _read_sprite_data_js()

    try:
        messages = apply_sprite_data(data)
        for msg in messages:
            print(msg)
    except ValueError as e:
        print(f"Error: {e}")
        sys.exit(1)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Sprite editor tooling — export to browser, apply changes back"
    )
    sub = parser.add_subparsers(dest="command")

    sub.add_parser("export", help="Export sprite data and open editor")

    apply_parser = sub.add_parser("apply", help="Apply changes from editor")
    apply_parser.add_argument(
        "json_file", nargs="?", default=None,
        help="Path to JSON file (default: reads from sprite_data.js)",
    )

    args = parser.parse_args()

    if args.command == "apply":
        cmd_apply(args.json_file)
    else:
        cmd_export()


if __name__ == "__main__":
    main()
